==2325444== Memcheck, a memory error detector
==2325444== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2325444== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==2325444== Command: python3 /home/sam/working/SPECT_issues/resolution_issue_sirf.py
==2325444== 
==2325444== 
==2325444== HEAP SUMMARY:
==2325444==     in use at exit: 1,598,872 bytes in 1,375 blocks
==2325444==   total heap usage: 363,061 allocs, 361,686 frees, 260,764,947 bytes allocated
==2325444== 
==2325444== 320 bytes in 4 blocks are definitely lost in loss record 98 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x400F21D: malloc (rtld-malloc.h:56)
==2325444==    by 0x400F21D: resize_scopes (dl-open.c:295)
==2325444==    by 0x400F21D: dl_open_worker_begin (dl-open.c:707)
==2325444==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2325444==    by 0x400DF99: dl_open_worker (dl-open.c:782)
==2325444==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2325444==    by 0x400E34D: _dl_open (dl-open.c:883)
==2325444==    by 0x4A4A6BB: dlopen_doit (dlopen.c:56)
==2325444==    by 0x4B2EC27: _dl_catch_exception (dl-error-skeleton.c:208)
==2325444==    by 0x4B2ECF2: _dl_catch_error (dl-error-skeleton.c:227)
==2325444==    by 0x4A4A1AD: _dlerror_run (dlerror.c:138)
==2325444==    by 0x4A4A747: dlopen_implementation (dlopen.c:71)
==2325444==    by 0x4A4A747: dlopen@@GLIBC_2.34 (dlopen.c:81)
==2325444==    by 0x36D60A: ??? (in /usr/bin/python3.10)
==2325444== 
==2325444== 536 bytes in 1 blocks are possibly lost in loss record 105 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x2764E0: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 568 bytes in 1 blocks are possibly lost in loss record 110 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 608 bytes in 1 blocks are possibly lost in loss record 190 of 363
==2325444==    at 0x484DCD3: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x349CAC: _PyObject_GC_Resize (in /usr/bin/python3.10)
==2325444==    by 0x24FF8F: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x2764E0: ??? (in /usr/bin/python3.10)
==2325444== 
==2325444== 624 bytes in 1 blocks are possibly lost in loss record 192 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2764AF: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x25D82C: _PyObject_FastCallDictTstate (in /usr/bin/python3.10)
==2325444==    by 0x27354B: _PyObject_Call_Prepend (in /usr/bin/python3.10)
==2325444==    by 0x38C1DF: ??? (in /usr/bin/python3.10)
==2325444==    by 0x25E5EA: _PyObject_MakeTpCall (in /usr/bin/python3.10)
==2325444==    by 0x257907: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x2764E0: ??? (in /usr/bin/python3.10)
==2325444== 
==2325444== 664 bytes in 1 blocks are possibly lost in loss record 197 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x2568A1: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 704 bytes in 1 blocks are possibly lost in loss record 199 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x25D753: _PyObject_FastCallDictTstate (in /usr/bin/python3.10)
==2325444==    by 0x2AA5AC: ??? (in /usr/bin/python3.10)
==2325444==    by 0x25E536: _PyObject_MakeTpCall (in /usr/bin/python3.10)
==2325444==    by 0x25B982: ??? (in /usr/bin/python3.10)
==2325444==    by 0x25B50A: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x341E55: ??? (in /usr/bin/python3.10)
==2325444==    by 0x341CF5: PyEval_EvalCode (in /usr/bin/python3.10)
==2325444==    by 0x347B0C: ??? (in /usr/bin/python3.10)
==2325444== 
==2325444== 832 bytes in 1 blocks are possibly lost in loss record 204 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x229637: _PyObject_GC_NewVar (in /usr/bin/python3.10)
==2325444==    by 0x24FE7C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2686DD: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 1,068 bytes in 1 blocks are possibly lost in loss record 220 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x247F6E: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2460C4: ??? (in /usr/bin/python3.10)
==2325444==    by 0x246A7E: ??? (in /usr/bin/python3.10)
==2325444==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2325444==    by 0x34131F: ??? (in /usr/bin/python3.10)
==2325444==    by 0x3512A4: ??? (in /usr/bin/python3.10)
==2325444==    by 0x267853: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2568A1: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x2520D0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 6,960 bytes in 15 blocks are possibly lost in loss record 343 of 363
==2325444==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x40147D9: calloc (rtld-malloc.h:44)
==2325444==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==2325444==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==2325444==    by 0x4A4F834: allocate_stack (allocatestack.c:430)
==2325444==    by 0x4A4F834: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==2325444==    by 0x307D225F: ??? (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==2325444==    by 0x307C8A10: GOMP_parallel (in /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0)
==2325444==    by 0x507CA0E3: stir::BackProjectorByBin::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (BackProjectorByBin.cxx:86)
==2325444==    by 0x508269CA: stir::ProjectorByBinPair::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (ProjectorByBinPair.cxx:49)
==2325444==    by 0x50826DBC: stir::ProjectorByBinPairUsingProjMatrixByBin::set_up(std::shared_ptr<stir::ProjDataInfo const> const&, std::shared_ptr<stir::DiscretisedDensity<3, float> const> const&) (ProjectorByBinPairUsingProjMatrixByBin.cxx:89)
==2325444==    by 0x506AB88A: sirf::PETAcquisitionModel::set_up(std::shared_ptr<sirf::STIRAcquisitionData>, std::shared_ptr<sirf::STIRImageData>) (stir_x.cpp:482)
==2325444==    by 0x5067497A: sirf::PETAcquisitionModelUsingMatrix::set_up(std::shared_ptr<sirf::STIRAcquisitionData>, std::shared_ptr<sirf::STIRImageData>) (stir_x.h:803)
==2325444==    by 0x5066308B: cSTIR_setupAcquisitionModel (cstir.cpp:678)
==2325444==    by 0x50638EBB: _wrap_cSTIR_setupAcquisitionModel (pystirPYTHON_wrap.cxx:3952)
==2325444== 
==2325444== 45,827 bytes in 22 blocks are possibly lost in loss record 356 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x247F6E: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2460C4: ??? (in /usr/bin/python3.10)
==2325444==    by 0x246948: ??? (in /usr/bin/python3.10)
==2325444==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2325444==    by 0x246A7E: ??? (in /usr/bin/python3.10)
==2325444==    by 0x24652B: ??? (in /usr/bin/python3.10)
==2325444==    by 0x34131F: ??? (in /usr/bin/python3.10)
==2325444==    by 0x3512A4: ??? (in /usr/bin/python3.10)
==2325444==    by 0x267853: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2568A1: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== 127,030 bytes in 70 blocks are possibly lost in loss record 359 of 363
==2325444==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2325444==    by 0x2900C7: PyUnicode_Substring (in /usr/bin/python3.10)
==2325444==    by 0x277B27: ??? (in /usr/bin/python3.10)
==2325444==    by 0x250F51: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444==    by 0x250E0C: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x341E55: ??? (in /usr/bin/python3.10)
==2325444==    by 0x341CF5: PyEval_EvalCode (in /usr/bin/python3.10)
==2325444==    by 0x347B0C: ??? (in /usr/bin/python3.10)
==2325444==    by 0x268968: ??? (in /usr/bin/python3.10)
==2325444==    by 0x2532C0: _PyEval_EvalFrameDefault (in /usr/bin/python3.10)
==2325444==    by 0x26870B: _PyFunction_Vectorcall (in /usr/bin/python3.10)
==2325444== 
==2325444== LEAK SUMMARY:
==2325444==    definitely lost: 320 bytes in 4 blocks
==2325444==    indirectly lost: 0 bytes in 0 blocks
==2325444==      possibly lost: 185,421 bytes in 115 blocks
==2325444==    still reachable: 1,413,131 bytes in 1,256 blocks
==2325444==         suppressed: 0 bytes in 0 blocks
==2325444== Reachable blocks (those to which a pointer was found) are not shown.
==2325444== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2325444== 
==2325444== For lists of detected and suppressed errors, rerun with: -s
==2325444== ERROR SUMMARY: 12 errors from 12 contexts (suppressed: 0 from 0)
